### ISSUE TITLE
make resource uri field hyperlink

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#310] opened 2020-06-18 19:43 UTC
e.g. 

/repositories/2/archival_objects/68861
https://specialcollections.du.edu/object/8c294ab6-0a67-4624-9af8-c1bb5846003c
they're removing archivesspace link to main website

**Comment by jrynhart** [comment] 2020-10-01 22:00
Duplicate of #344

**Closed by jrynhart** 2020-10-01 22:00 UTC
